FATAL:   Image file already exists: "/gpfs/home/jl24018/openmm-md.sif" - will not overwrite
2024-11-18 11:40:20,123 - src.plumed.main - INFO - Output directory: ../../data/241109_INFconstruct/output/Z1-B50W/241118_2
2024-11-18 11:40:20,124 - src.plumed.main - INFO - ==================== Running Z1-B50W ====================
2024-11-18 11:40:20,124 - src.plumed.main - INFO - Running with timestep 2 fs and mdtime 2 ns
2024-11-18 11:40:20,124 - src.plumed.main - INFO - Energy barrier 200 kJ/mol for OPES
2024-11-18 11:40:20,124 - src.plumed.main - INFO - Pace 500 steps of depositing bias in OPES.
/opt/conda/lib/python3.12/site-packages/MDAnalysis/topology/PDBParser.py:290: UserWarning: PDB file is missing resid information.  Defaulted to '1'
  warnings.warn("PDB file is missing resid information.  "
/opt/conda/lib/python3.12/site-packages/MDAnalysis/topology/PDBParser.py:304: UserWarning: Serial numbers went over 100,000.  Higher serials have been guessed
  warnings.warn("Serial numbers went over 100,000.  "
/opt/conda/lib/python3.12/site-packages/MDAnalysis/topology/PDBParser.py:423: UserWarning: Invalid atom serials were present, bonds will not be parsed
  warnings.warn("Invalid atom serials were present, bonds will not"
/opt/conda/lib/python3.12/site-packages/MDAnalysis/topology/PDBParser.py:215: UserWarning: Invalid atom serials were present, bonds will not be parsed
  warnings.warn("Invalid atom serials were present, "
2024-11-18 11:42:02,797 - src.plumed.opes - INFO - Using CUDA device 1,0
Traceback (most recent call last):
  File "/gpfs/home/jl24018/projects/openmm-md/scripts/241118_INFconstruct/run.py", line 73, in <module>
    print(f"CUDA_VISIBLE_DEVICES: {os.environ.get('CUDA_VISIBLE_DEVICES')}")
  File "/gpfs/home/jl24018/projects/openmm-md/src/plumed/main.py", line 102, in main
    opes(
  File "/gpfs/home/jl24018/projects/openmm-md/src/plumed/opes.py", line 161, in opes
    simulation = Simulation(topology, system, integrator, platform, properties)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.12/site-packages/openmm/app/simulation.py", line 106, in __init__
    self.context = mm.Context(self.system, self.integrator, platform, platformProperties)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.12/site-packages/openmm/openmm.py", line 15566, in __init__
    _openmm.Context_swiginit(self, _openmm.new_Context(*args))
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
openmm.OpenMMException: Illegal value for DeviceIndex: 1
